apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-web
  labels:
    app: {{ .Chart.Name }}-web
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-web
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        command: ["/goapp"]
        ports:
        - containerPort: {{ .Values.app.containerPort }}

