{{ $domain := .Values.app.domain }}
{{ $servicePort := .Values.app.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-web
spec:
  rules:
  - host: {{ $domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-web
            port:
              number: {{ $servicePort }}

