apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
spec:
  selector:
    app: {{ .Chart.Name }}-web
  ports:
    - protocol: TCP
      port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}

